<?php
namespace backend\module;

use yii\web\Controller;
use backend\services\PowerService;

class BaseController extends Controller
{
    public $adminInfo = [];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        //判断是否登录
        $session = \Yii::$app->session;
        $this->adminInfo = $session->get('adminInfo');
        if(!$this->adminInfo) {
            return $this->redirect(['/login/login/login']);
        }

        $adminInfo = \Yii::$app->session->get('adminInfo');
        $position_id = $adminInfo['position_id'];
        $positionPowerList = PowerService::getPowerList();
        $view = \YII::$app->view;
        $view->params['menu'] = $positionPowerList;



    }


}