<?php
namespace backend\module;

use app\models\RPower;
use yii\web\Controller;
use backend\services\PowerService;
use app\models\RPositionPower;

class BaseController extends Controller
{
    public $adminInfo = [];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $view = \YII::$app->view;

        //判断是否登录
        $session = \Yii::$app->session;
        $this->adminInfo = $session->get('adminInfo');
        if(!$this->adminInfo) {
            return $this->redirect(['/login/login/login']);
        }

        $adminInfo = \Yii::$app->session->get('adminInfo');
        $position_id = $adminInfo['position_id'];
        $view->params['position_id'] = $position_id;


        $positionPower = RPositionPower::find()->select('power_id')->where(['position_id' => $position_id])->asArray()->all();
        $power_id = array_column($positionPower,'power_id');
        $view->params['power_id'] = $power_id;

        $positionPowerList = PowerService::getPowerList();
        $view->params['menu'] = $positionPowerList;

        //判断是否有权限操作
//        echo $this->module->id;
//        echo $this->id;
//        print_r($this->action->id) ;
//        die;




    }


}