<?php
namespace backend\module;

use yii\web\Controller;
use backend\services\PowerService;

class BaseController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $adminInfo = \Yii::$app->session->get('adminInfo');
        $position_id = $adminInfo['position_id'];
        $positionPowerList = PowerService::getPowerList();
        $view = \YII::$app->view;
        $view->params['menu'] = $positionPowerList;
    }


}